const data = {
  productData: [
    {
      id: 1,
      img: "https://source.unsplash.com/420x220/?mobile",
      title: "Mobile",
      decs: "",
      price: 10000,
    },
    {
      id: 2,
      img: "https://source.unsplash.com/420x220/?watch",
      title: "Watch",
      decs: "",
      price: 2000,
    },
    {
      id: 3,
      img: "https://source.unsplash.com/420x220/?keyboard",
      title: "Keyboard",
      decs: "",
      price: 4500,
    },
    {
      id: 4,
      img: "https://source.unsplash.com/420x220/?camera",
      title: "Camera",
      decs: "",
      price: 2000,
    },
    {
      id: 5,
      img: "https://source.unsplash.com/420x220/?television",
      title: "Television",
      decs: "",
      price: 5000,
    },
    {
      id: 6,
      img: "https://source.unsplash.com/420x220/?computermouse",
      title: "Mouse",
      decs: "",
      price: 1800,
    },
    {
      id: 7,
      img: "https://source.unsplash.com/420x220/?book",
      title: "Books",
      decs: "",
      price: 500,
    },
    {
      id: 8,
      img: "https://source.unsplash.com/420x220/?bedding",
      title: "Bedding",
      decs: "",
      price: 2000,
    },
    {
      id: 9,
      img: "https://source.unsplash.com/420x220/?Pillows",
      title: "Pillows",
      decs: "",
      price: 2500,
    },
    {
      id: 10,
      img: "https://source.unsplash.com/420x220/?lumbar-pillows",
      title: "Lumbar Pillows",
      decs: "",
      price: 2500,
    },
    {
      id: 11,
      img: "https://source.unsplash.com/420x220/?toys",
      title: "Toys & Games",
      decs: "",
      price: 2500,
    },
    {
      id: 12,
      img: "https://source.unsplash.com/420x220/?supplements",
      title: "Health & Household",
      decs: "",
      price: 2500,
    },
    {
      id: 13,
      img: "https://source.unsplash.com/420x220/?drawings",
      title: "Wall Art",
      decs: "",
      price: 2500,
    },
    {
      id: 14,
      img: "https://source.unsplash.com/420x220/?Boring-Bars",
      title: "Cutting Tools",
      decs: "",
      price: 2500,
    },
    {
      id: 15,
      img: "https://source.unsplash.com/420x220/?mobile",
      title: "Mobile",
      decs: "",
      price: 10000,
    },
    {
      id: 16,
      img: "https://source.unsplash.com/420x220/?watch",
      title: "Watch",
      decs: "",
      price: 2000,
    },
    {
      id: 17,
      img: "https://source.unsplash.com/420x220/?keyboard",
      title: "Keyboard",
      decs: "",
      price: 4500,
    },
    {
      id: 18,
      img: "https://source.unsplash.com/420x220/?camera",
      title: "Camera",
      decs: "",
      price: 2000,
    },
    {
      id: 19,
      img: "https://source.unsplash.com/420x220/?television",
      title: "Television",
      decs: "",
      price: 5000,
    },
    {
      id: 20,
      img: "https://source.unsplash.com/420x220/?bedding",
      title: "Bedding",
      decs: "",
      price: 2000,
    },
  ],
};

export default data;
